# Generated by Django 3.0.7 on 2020-06-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='department',
        ),
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.FloatField(null=True),
        ),
    ]
